language: python
python:
- '3.6'
script: true
deploy:
  provider: pypi
  user: fridex
  password:
    secure: ntg0l4taKDn89w8ZUpfUbPYqfJRFSyfVlQ7JTm3KbN4nGNj0tSHHJO+d8OlEEyz/iw3i67wNTC+LrHg79UvNvteuzdcXsUuYgXjQTv0C7Q+64myypQJD5abG3EuRSErawdD8xo/gq/Ygi8zfVJKov8Pzsf+AHEV1j/eVtdtXsdRYaNm3PUTWqSCmY2Fm3kPhT8GuSmOCEX0MsWNdMc12FOPV8TMgdFvwzvdxUipYv7Pq47X8ty+nwEpmKlBImMJX8hgwD36EofHGeqWXdB1i5S3UBXubvyUMaXALHjvPfycaMI7lhx18jCNxpuVkkZ6294noic9Os6kDSBcer/DYDS2Pi1cd4r/YEVnaZdLNV5wTfv2TvGK5SWtjatSi+q6heR+DX8QV8Pn/eK06a3KyIGKuMpKdExA63AIivbghxWEc7HhodGZuGWeIrVT69Yfsm+wKjLbdQ8a1cahKIWu92alWr6+V4g+Ew5R2HSHi3gGNBLnstjXtBXpUrU1Y6VNWGN4snTGqLe+iyUTyV5EpAhBWrpjxayP9iKwddCdRwbKRU+ryY4O4d/xqd7241O/HeT261+I/NzfOyuQizJ2m65MD8upNQafNPh7D/52OH+XIZv/XzYmS/u/WKQU52n8SZBMCWOJQVzil7ZOyszNfcAIQjSXmwlH7dozoAaQ9/kY=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
